# Generated by Django 3.1.3 on 2020-12-09 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Ingredientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='persons',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='porciones'),
            preserve_default=False,
        ),
    ]
