# Generated by Django 3.1.3 on 2020-12-09 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_auto_20201209_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cook',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Tiempo preparacion'),
            preserve_default=False,
        ),
    ]
