# Generated by Django 3.1.3 on 2020-12-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0003_post_cook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
