# Generated by Django 3.1.3 on 2020-12-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cook',
            field=models.CharField(default='', max_length=50, verbose_name='Tiempo preparacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default='', verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='persons',
            field=models.IntegerField(default=0, verbose_name='porciones'),
        ),
    ]
