# Generated by Django 3.1.3 on 2020-12-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0006_auto_20201209_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cook',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='post',
            name='persons',
        ),
    ]
