# Generated by Django 3.1.3 on 2020-12-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0007_auto_20201209_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='get_posts', to='receta.Category', verbose_name='Categorias'),
        ),
    ]
